<div id="user_ajax_fill">
    <div id="user_ajax_fill" class="">
        <div class="form-group has-success">
            <label class="col-sm-2 control-label">New owner first name aj</label>
            <div class="col-sm-4">
                <div class="form-control-wrapper">
                    <input type="text" name="owner_first_name" id="owner_first_name" class="form-control empty" placeholder="Owner first name" data-toggle="tooltip" data-placement="top" title="" value="" data-original-title="Insert owner first name">
                    <span class="material-input"></span>
                </div>                            
            </div>
            <label class="col-sm-2 control-label">New owner last name aj</label>
            <div class="col-sm-4">
                <div class="form-control-wrapper"><input type="text" name="owner_last_name" id="owner_last_name" class="form-control empty" placeholder="Owner last name" data-toggle="tooltip" data-placement="top" title="" value="" data-original-title="Insert owner last name"><span class="material-input"></span></div>                            </div>
        </div>
        <div class="form-group has-success has-feedback">
            <label class="col-sm-2 control-label">New owner email aj</label>
            <div class="col-sm-4">
                <div class="form-control-wrapper"><input type="text" name="owner_email" id="owner_email" class="form-control empty" required="required" placeholder="Owner email address" data-toggle="tooltip" data-placement="top" title="" value="" data-original-title="Insert owner email address"><span class="material-input"></span></div>                                <span class="fa fa-envelope-o txt-success form-control-feedback"></span>
            </div>
            <label class="col-sm-2 control-label">New owner address aj</label>
            <div class="col-sm-4">
                <div class="form-control-wrapper"><input type="text" name="owner_address" id="owner_address" class="form-control empty" placeholder="Owner address" data-toggle="tooltip" data-placement="top" title="" value="" data-original-title="Insert owner address"><span class="material-input"></span></div>                                <span class="fa fa-map-marker txt-success form-control-feedback"></span>
            </div>
        </div>
        <div class="form-group has-success has-feedback">
            <label class="col-sm-2 control-label">New owner telephone aj</label>
            <div class="col-sm-4">
                <div class="form-control-wrapper"><input type="text" name="owner_phone" id="owner_phone" class="form-control empty" required="required" placeholder="Owner phone" data-toggle="tooltip" data-placement="top" title="" value="" data-original-title="Insert owner phone"><span class="material-input"></span></div>                                <span class="fa fa-phone form-control-feedback"></span>
            </div>
        </div>
    </div>
    
    
    
    
    
    
<!--    
    <div class="form-group has-success">
        <label class="col-sm-2 control-label"><?//=$this->translate('New owner first name')?></label>
        <div class="col-sm-4">
            <?//=$this->formRow($form->get('owner_first_name'));?>
        </div>
        <label class="col-sm-2 control-label"><?//=$this->translate('New owner last name')?></label>
        <div class="col-sm-4">
            <?//=$this->formRow($form->get('owner_last_name'));?>
        </div>
    </div>
    <div class="form-group has-success has-feedback">
        <label class="col-sm-2 control-label"><?//=$this->translate('New owner email')?></label>
        <div class="col-sm-4">
            <?//=$this->formRow($form->get('owner_email'));?>
            <span class="fa fa-envelope-o txt-success form-control-feedback"></span>
        </div>
        <label class="col-sm-2 control-label"><?//=$this->translate('New owner address')?></label>
        <div class="col-sm-4">
            <?//=$this->formRow($form->get('owner_address'));?>
            <span class="fa fa-map-marker txt-success form-control-feedback"></span>
        </div>
    </div>
    <div class="form-group has-success has-feedback">
        <label class="col-sm-2 control-label"><?//=$this->translate('New owner telephone')?></label>
        <div class="col-sm-4">
            <?//=$this->formRow($form->get('owner_phone'));?>
            <span class="fa fa-phone form-control-feedback"></span>
        </div>
    </div>-->
</div>

 