<ol class="breadcrumb">
    <?php
    foreach ($this->pages as $key => $page):
        ?>
        <li>
            <?php
            if ($key < count($this->pages) - 1):
                ?>
                <a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>
            <?php
            else:
            ?>
                <a href="javascript::void(0)"><?php echo $page->getLabel(); ?></a>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ol>