<?php

/* 
 * @category   Booking Software
 * @package    Srider Module
 * @author     Brinzaru Andrei-Dan <dan.brinzaru@gmail.com>
 * @copyright  Copyright (c) 2016 - Technicopro, Brinzaru Andrei-Dan
 * @version    1.0
 */

    $title = $this->translate('Srider - Index');
    $this->headTitle($title);
    
    $this->headLink()
                    ->prependStylesheet($this->basePath('css/srider/srider.css')) 
                    ->prependStylesheet($this->basePath('plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css'));
    $this->headScript()->appendFile('/plugins/moment/min/moment-with-locales.min.js');
    $this->headScript()->appendFile('plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js');
    $this->headScript()->appendFile('/js/srider/srider.js');
    

?> 
 

<a href="<?php echo $this->url('home')."cn";?>"><?php echo $this->translate("Chinese");?></a>
<a href="<?php echo $this->url('home')."en";?>"><?php echo $this->translate("English");?></a>
    <h1 class="page-header">
        <?php echo $this->translate('Srider homepage') ?>
    </h1>

<div class="col-sm-12 col-md-12 jumbotron"> 
    <div class="row">
        <?php 
            $form = $this->bookForm;
            $form->prepare();
            echo $this->form()->openTag($form);
        ?>
        <div class="col-sm-4" id="point_a">
            <?=$this->formElement($form->get('pick_up_location')); ?>
            <span class="common-error-msg"><?=$this->formElementErrors($form->get('pick_up_location'));?></span> 
        </div>

        <div class="col-sm-2">
            <?=$this->formElement($form->get('pick_up_date')); ?>
            <span class="common-error-msg"><?=$this->formElementErrors($form->get('pick_up_date'));?></span> 
        </div>

        <div class="col-sm-2">
            <?=$this->formElement($form->get('pick_up_time')); ?>
            <span class="common-error-msg"><?=$this->formElementErrors($form->get('pick_up_time'));?></span> 
        </div>

        <div class="col-sm-4" id="point_b">
            <?=$this->formElement($form->get('destination_location')); ?>
            <span class="common-error-msg"><?=$this->formElementErrors($form->get('destination_location'));?></span> 
        </div>
        <div id="mode-selector" class="controls" style="display:none;">
        <input type="radio" name="type" id="changemode-walking" >
        <label for="changemode-walking">Walking</label>

        <input type="radio" name="type" id="changemode-transit">
        <label for="changemode-transit">Transit</label>

        <input type="radio" name="type" id="changemode-driving" checked="checked">
        <label for="changemode-driving">Driving</label>
    </div>
<!--        <div id="mode-selector" class="controls lalatype"  >
           <?//=$this->formElement($form->get('type')); ?>
        </div>-->
    </div> 

    <div class="row">
        <div class="col-sm-4 col-sm-offset-4 col-md-offset-4">
            <?=$this->formElement($form->get('submit_booking'));?> 
        </div>
    </div>
    <?=$this->form()->closeTag($form);?>

</div>

<div class="modal" id="complete-dialog">    
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <div class="row col-sm-12">
                    <div class="col-sm-6 col-md-6 pull-left">
                        eeew<br/>wwwww<br/>wwwww<br/>wwwwwwww<br/>wwwwwwwwww<br/>wwwwwwwwwwww<br/>wwwwwwwwwwww<br/>wwww<br/>wwwwww<br/>wwwww<br/>wwwwww<br/>wwwwwwwwwwww
                    </div>
                    <div class="col-sm-6 col-md-6 pull-left">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
      </div>
    </div>
</div>

<div id="map"></div>

   
<script>
    function initMap() {
        var origin_place_id = null;
        var destination_place_id = null;
        var travel_mode = google.maps.TravelMode.WALKING;
        var map = new google.maps.Map(document.getElementById('map'), {
            mapTypeControl: false,
            center: {lat: -33.8688, lng: 151.2195},
            zoom: 13
        });
        var directionsService = new google.maps.DirectionsService;
        var directionsDisplay = new google.maps.DirectionsRenderer;
        directionsDisplay.setMap(map);

        var origin_input = document.getElementById('origin-input');
        var destination_input = document.getElementById('destination-input');
        var modes = document.getElementById('mode-selector');

        map.controls[google.maps.ControlPosition.TOP_LEFT].push(origin_input);
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(destination_input);
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(modes);

        var origin_autocomplete = new google.maps.places.Autocomplete(origin_input);
        origin_autocomplete.bindTo('bounds', map);
        var destination_autocomplete =
            new google.maps.places.Autocomplete(destination_input);
        destination_autocomplete.bindTo('bounds', map);


        function setupClickListener(id, mode) {
            var radioButton = document.getElementById(id);
            radioButton.addEventListener('click', function() {
              travel_mode = mode;
            });
        }
        setupClickListener('changemode-walking', google.maps.TravelMode.WALKING);
        setupClickListener('changemode-transit', google.maps.TravelMode.TRANSIT);
        setupClickListener('changemode-driving', google.maps.TravelMode.DRIVING);

        function expandViewportToFitPlace(map, place) {
            if (place.geometry.viewport) {
              map.fitBounds(place.geometry.viewport);
            } else {
              map.setCenter(place.geometry.location);
              map.setZoom(17);
            }
        }

        origin_autocomplete.addListener('place_changed', function() {
            var place = origin_autocomplete.getPlace();
            if (!place.geometry) {
              window.alert("Autocomplete's returned place contains no geometry");
              return;
            }
            expandViewportToFitPlace(map, place);

            origin_place_id = place.place_id;
            route(origin_place_id, destination_place_id, travel_mode,
                    directionsService, directionsDisplay);
        });

        destination_autocomplete.addListener('place_changed', function() {
            var place = destination_autocomplete.getPlace();
            if (!place.geometry) {
              window.alert("Autocomplete's returned place contains no geometry");
              return;
            }
            expandViewportToFitPlace(map, place);

            destination_place_id = place.place_id;
            route(origin_place_id, destination_place_id, travel_mode,
                    directionsService, directionsDisplay);
        });

        function route(origin_place_id, destination_place_id, travel_mode,
                       directionsService, directionsDisplay) {
            if (!origin_place_id || !destination_place_id) {
              return;
            }
            directionsService.route({
              origin: {'placeId': origin_place_id},
              destination: {'placeId': destination_place_id},
              travelMode: travel_mode
            }, function(response, status) {
              if (status === google.maps.DirectionsStatus.OK) {
                directionsDisplay.setDirections(response);
              } else {
                window.alert('Directions request failed due to ' + status);
              }
            });
        }
    }
    $("#origin-input").prependTo("#point_a");
    $("#destination-input").prependTo("#point_b");
</script>
  
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDzuttas9x9Io2J3U4EhoabiGF1mF4iLtE&libraries=places&callback=initMap"
        async defer></script>
        
<script>
    $(document).ready(function() { 
      $(window).load(function() { 
         $("#origin-input").prependTo("#point_a");
         $("#destination-input").prependTo("#point_b");
      });
    });
</script>